Better README file
taubyte/go-seer pull request #2
Opened 2022-12-20 23:11 UTC by taubyte0

2022-12-20 23:28 UTC, arontaubyte commented on README.md
> +Note tha you can also use a virtual file system
Note that

2022-12-20 23:56 UTC, tafseer-khan requested changes

2022-12-20 23:56 UTC, tafseer-khan commented on README.md
> +The import path for the package is *gothub.com/taubyte/go-seer*.
gothub?

2022-12-20 23:56 UTC, tafseer-khan commented on README.md
> +go get gothub.com/taubyte/go-seer
gothub?!?

2022-12-20 23:56 UTC, tafseer-khan commented on README.md
> +Seer is a powerfull tool to parse and edit Yaml files in a folder as if they represent one structure.
Go-seer is a tool to parse and edit YAML files in a directory as one structure.

if you want to add powerful, powerful has one L

2022-12-20 23:56 UTC, tafseer-khan commented on README.md
> +First start by creating an instance of seer
of go-seer

2022-12-20 23:56 UTC, tafseer-khan commented on README.md
> +Note tha you can also use a virtual file system
Note that you can also use a virtual file system.

2022-12-21 00:02 UTC, tafseer-khan approved these changes

2022-12-21 00:29 UTC, merged